package es.upv.dsic.quep.model;
// Generated 04-ago-2016 14:00:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaturityLevelPracticeId generated by hbm2java
 */
@Embeddable
public class MaturityLevelPracticeId  implements java.io.Serializable {


     private int idPractice;
     private int idMaturityLevel;

    public MaturityLevelPracticeId() {
    }

    public MaturityLevelPracticeId(int idPractice, int idMaturityLevel) {
       this.idPractice = idPractice;
       this.idMaturityLevel = idMaturityLevel;
    }
   


    @Column(name="id_practice", nullable=false)
    public int getIdPractice() {
        return this.idPractice;
    }
    
    public void setIdPractice(int idPractice) {
        this.idPractice = idPractice;
    }


    @Column(name="id_maturity_level", nullable=false)
    public int getIdMaturityLevel() {
        return this.idMaturityLevel;
    }
    
    public void setIdMaturityLevel(int idMaturityLevel) {
        this.idMaturityLevel = idMaturityLevel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaturityLevelPracticeId) ) return false;
		 MaturityLevelPracticeId castOther = ( MaturityLevelPracticeId ) other; 
         
		 return (this.getIdPractice()==castOther.getIdPractice())
 && (this.getIdMaturityLevel()==castOther.getIdMaturityLevel());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPractice();
         result = 37 * result + this.getIdMaturityLevel();
         return result;
   }   


}


