package es.upv.dsic.quep.model;
// Generated 20-oct-2016 20:22:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuepQuestionTechniqueId generated by hbm2java
 */
@Embeddable
public class QuepQuestionTechniqueId  implements java.io.Serializable {


     private int idTechnique;
     private int idQuestion;

    public QuepQuestionTechniqueId() {
    }

    public QuepQuestionTechniqueId(int idTechnique, int idQuestion) {
       this.idTechnique = idTechnique;
       this.idQuestion = idQuestion;
    }
   


    @Column(name="id_technique", nullable=false)
    public int getIdTechnique() {
        return this.idTechnique;
    }
    
    public void setIdTechnique(int idTechnique) {
        this.idTechnique = idTechnique;
    }


    @Column(name="id_question", nullable=false)
    public int getIdQuestion() {
        return this.idQuestion;
    }
    
    public void setIdQuestion(int idQuestion) {
        this.idQuestion = idQuestion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuepQuestionTechniqueId) ) return false;
		 QuepQuestionTechniqueId castOther = ( QuepQuestionTechniqueId ) other; 
         
		 return (this.getIdTechnique()==castOther.getIdTechnique())
 && (this.getIdQuestion()==castOther.getIdQuestion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTechnique();
         result = 37 * result + this.getIdQuestion();
         return result;
   }   


}


