package es.upv.dsic.quep.model;
// Generated 20-oct-2016 20:22:12 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuepQuestionResponseOption generated by hbm2java
 */
@Entity
@Table(name="quep_question_response_option"
    ,schema="public"
)
public class QuepQuestionResponseOption  implements java.io.Serializable {


     private QuepQuestionResponseOptionId id;
     private QuepQuestion quepQuestion;
     private ResponseOption responseOption;
     private String creationUser;
     private Date creationDate;
     private String modificationUser;
     private Date modificationDate;
     private int active;
     private String audit;
     private int idPrinciple;
     private int idPractice;

    public QuepQuestionResponseOption() {
    }

	
    public QuepQuestionResponseOption(QuepQuestionResponseOptionId id, QuepQuestion quepQuestion, ResponseOption responseOption, String creationUser, Date creationDate, int active, String audit, int idPrinciple, int idPractice) {
        this.id = id;
        this.quepQuestion = quepQuestion;
        this.responseOption = responseOption;
        this.creationUser = creationUser;
        this.creationDate = creationDate;
        this.active = active;
        this.audit = audit;
        this.idPrinciple = idPrinciple;
        this.idPractice = idPractice;
    }
    public QuepQuestionResponseOption(QuepQuestionResponseOptionId id, QuepQuestion quepQuestion, ResponseOption responseOption, String creationUser, Date creationDate, String modificationUser, Date modificationDate, int active, String audit, int idPrinciple, int idPractice) {
       this.id = id;
       this.quepQuestion = quepQuestion;
       this.responseOption = responseOption;
       this.creationUser = creationUser;
       this.creationDate = creationDate;
       this.modificationUser = modificationUser;
       this.modificationDate = modificationDate;
       this.active = active;
       this.audit = audit;
       this.idPrinciple = idPrinciple;
       this.idPractice = idPractice;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idQuepQuestion", column=@Column(name="id_quep_question", nullable=false) ), 
        @AttributeOverride(name="idResponseOption", column=@Column(name="id_response_option", nullable=false) ) } )
    public QuepQuestionResponseOptionId getId() {
        return this.id;
    }
    
    public void setId(QuepQuestionResponseOptionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_quep_question", nullable=false, insertable=false, updatable=false)
    public QuepQuestion getQuepQuestion() {
        return this.quepQuestion;
    }
    
    public void setQuepQuestion(QuepQuestion quepQuestion) {
        this.quepQuestion = quepQuestion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_response_option", nullable=false, insertable=false, updatable=false)
    public ResponseOption getResponseOption() {
        return this.responseOption;
    }
    
    public void setResponseOption(ResponseOption responseOption) {
        this.responseOption = responseOption;
    }

    
    @Column(name="creation_user", nullable=false)
    public String getCreationUser() {
        return this.creationUser;
    }
    
    public void setCreationUser(String creationUser) {
        this.creationUser = creationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="modification_user")
    public String getModificationUser() {
        return this.modificationUser;
    }
    
    public void setModificationUser(String modificationUser) {
        this.modificationUser = modificationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modification_date", length=13)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }

    
    @Column(name="audit", nullable=false)
    public String getAudit() {
        return this.audit;
    }
    
    public void setAudit(String audit) {
        this.audit = audit;
    }

    
    @Column(name="id_principle", nullable=false)
    public int getIdPrinciple() {
        return this.idPrinciple;
    }
    
    public void setIdPrinciple(int idPrinciple) {
        this.idPrinciple = idPrinciple;
    }

    
    @Column(name="id_practice", nullable=false)
    public int getIdPractice() {
        return this.idPractice;
    }
    
    public void setIdPractice(int idPractice) {
        this.idPractice = idPractice;
    }




}


