package es.upv.dsic.quep.model;
// Generated 20-oct-2016 20:22:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionType generated by hbm2java
 */
@Entity
@Table(name="question_type"
    ,schema="public"
)
public class QuestionType  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer itemNumber;
     private String creationUser;
     private Date creationDate;
     private String modificationUser;
     private Date modificationDate;
     private int active;
     private String audit;
     private Set<QuepQuestion> quepQuestions = new HashSet<QuepQuestion>(0);
     private Set<ResponseOption> responseOptions = new HashSet<ResponseOption>(0);

    public QuestionType() {
    }

	
    public QuestionType(int id, String creationUser, Date creationDate, int active, String audit) {
        this.id = id;
        this.creationUser = creationUser;
        this.creationDate = creationDate;
        this.active = active;
        this.audit = audit;
    }
    public QuestionType(int id, String name, Integer itemNumber, String creationUser, Date creationDate, String modificationUser, Date modificationDate, int active, String audit, Set<QuepQuestion> quepQuestions, Set<ResponseOption> responseOptions) {
       this.id = id;
       this.name = name;
       this.itemNumber = itemNumber;
       this.creationUser = creationUser;
       this.creationDate = creationDate;
       this.modificationUser = modificationUser;
       this.modificationDate = modificationDate;
       this.active = active;
       this.audit = audit;
       this.quepQuestions = quepQuestions;
       this.responseOptions = responseOptions;
    }
    
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) //add to mapped
    
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="item_number")
    public Integer getItemNumber() {
        return this.itemNumber;
    }
    
    public void setItemNumber(Integer itemNumber) {
        this.itemNumber = itemNumber;
    }

    
    @Column(name="creation_user", nullable=false)
    public String getCreationUser() {
        return this.creationUser;
    }
    
    public void setCreationUser(String creationUser) {
        this.creationUser = creationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="modification_user")
    public String getModificationUser() {
        return this.modificationUser;
    }
    
    public void setModificationUser(String modificationUser) {
        this.modificationUser = modificationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modification_date", length=13)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }

    
    @Column(name="audit", nullable=false)
    public String getAudit() {
        return this.audit;
    }
    
    public void setAudit(String audit) {
        this.audit = audit;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questionType")
    public Set<QuepQuestion> getQuepQuestions() {
        return this.quepQuestions;
    }
    
    public void setQuepQuestions(Set<QuepQuestion> quepQuestions) {
        this.quepQuestions = quepQuestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questionType")
    public Set<ResponseOption> getResponseOptions() {
        return this.responseOptions;
    }
    
    public void setResponseOptions(Set<ResponseOption> responseOptions) {
        this.responseOptions = responseOptions;
    }




}


