package es.upv.dsic.quep.model;
// Generated 20-oct-2016 20:22:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionnaireId generated by hbm2java
 */
@Embeddable
public class QuestionnaireId  implements java.io.Serializable {


     private int id;
     private int idPractice;
     private int idRole;

    public QuestionnaireId() {
    }

    public QuestionnaireId(int id, int idPractice, int idRole) {
       this.id = id;
       this.idPractice = idPractice;
       this.idRole = idRole;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="id_practice", nullable=false)
    public int getIdPractice() {
        return this.idPractice;
    }
    
    public void setIdPractice(int idPractice) {
        this.idPractice = idPractice;
    }


    @Column(name="id_role", nullable=false)
    public int getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionnaireId) ) return false;
		 QuestionnaireId castOther = ( QuestionnaireId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getIdPractice()==castOther.getIdPractice())
 && (this.getIdRole()==castOther.getIdRole());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getIdPractice();
         result = 37 * result + this.getIdRole();
         return result;
   }   


}


