package es.upv.dsic.quep.model;
// Generated 20-oct-2016 20:22:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResponseOption generated by hbm2java
 */
@Entity
@Table(name="response_option"
    ,schema="public"
)
public class ResponseOption  implements java.io.Serializable {


     private int id;
     private QuestionType questionType;
     private String name;
     private String creationUser;
     private Date creationDate;
     private String modificationUser;
     private Date modificationDate;
     private int active;
     private String audit;
     private BigDecimal weight;
     private Integer isRequiered;
     private Set<QuepQuestionResponseOption> quepQuestionResponseOptions = new HashSet<QuepQuestionResponseOption>(0);
     private Set<Response> responses = new HashSet<Response>(0);

    public ResponseOption() {
    }

	
    public ResponseOption(int id, QuestionType questionType, String name, String creationUser, Date creationDate, int active, String audit) {
        this.id = id;
        this.questionType = questionType;
        this.name = name;
        this.creationUser = creationUser;
        this.creationDate = creationDate;
        this.active = active;
        this.audit = audit;
    }
    public ResponseOption(int id, QuestionType questionType, String name, String creationUser, Date creationDate, String modificationUser, Date modificationDate, int active, String audit, BigDecimal weight, Integer isRequiered, Set<QuepQuestionResponseOption> quepQuestionResponseOptions, Set<Response> responses) {
       this.id = id;
       this.questionType = questionType;
       this.name = name;
       this.creationUser = creationUser;
       this.creationDate = creationDate;
       this.modificationUser = modificationUser;
       this.modificationDate = modificationDate;
       this.active = active;
       this.audit = audit;
       this.weight = weight;
       this.isRequiered = isRequiered;
       this.quepQuestionResponseOptions = quepQuestionResponseOptions;
       this.responses = responses;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) //add to mapped
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_question_type", nullable=false)
    public QuestionType getQuestionType() {
        return this.questionType;
    }
    
    public void setQuestionType(QuestionType questionType) {
        this.questionType = questionType;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="creation_user", nullable=false)
    public String getCreationUser() {
        return this.creationUser;
    }
    
    public void setCreationUser(String creationUser) {
        this.creationUser = creationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="modification_user")
    public String getModificationUser() {
        return this.modificationUser;
    }
    
    public void setModificationUser(String modificationUser) {
        this.modificationUser = modificationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modification_date", length=13)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }

    
    @Column(name="audit", nullable=false)
    public String getAudit() {
        return this.audit;
    }
    
    public void setAudit(String audit) {
        this.audit = audit;
    }

    
    @Column(name="weight", precision=5)
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    
    @Column(name="is_requiered")
    public Integer getIsRequiered() {
        return this.isRequiered;
    }
    
    public void setIsRequiered(Integer isRequiered) {
        this.isRequiered = isRequiered;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="responseOption")
    public Set<QuepQuestionResponseOption> getQuepQuestionResponseOptions() {
        return this.quepQuestionResponseOptions;
    }
    
    public void setQuepQuestionResponseOptions(Set<QuepQuestionResponseOption> quepQuestionResponseOptions) {
        this.quepQuestionResponseOptions = quepQuestionResponseOptions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="responseOption")
    public Set<Response> getResponses() {
        return this.responses;
    }
    
    public void setResponses(Set<Response> responses) {
        this.responses = responses;
    }




}


