package es.upv.dsic.quep.model;
// Generated 06-ago-2016 21:21:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleStakeholderId generated by hbm2java
 */
@Embeddable
public class RoleStakeholderId  implements java.io.Serializable {


     private int idRole;
     private int idStakeholder;

    public RoleStakeholderId() {
    }

    public RoleStakeholderId(int idRole, int idStakeholder) {
       this.idRole = idRole;
       this.idStakeholder = idStakeholder;
    }
   


    @Column(name="id_role", nullable=false)
    public int getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }


    @Column(name="id_stakeholder", nullable=false)
    public int getIdStakeholder() {
        return this.idStakeholder;
    }
    
    public void setIdStakeholder(int idStakeholder) {
        this.idStakeholder = idStakeholder;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RoleStakeholderId) ) return false;
		 RoleStakeholderId castOther = ( RoleStakeholderId ) other; 
         
		 return (this.getIdRole()==castOther.getIdRole())
 && (this.getIdStakeholder()==castOther.getIdStakeholder());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRole();
         result = 37 * result + this.getIdStakeholder();
         return result;
   }   


}


