package es.upv.dsic.quep.model;
// Generated 06-ago-2016 21:21:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RolePractice generated by hbm2java
 */
@Entity
@Table(name="role_practice"
    ,schema="public"
)
public class RolePractice  implements java.io.Serializable {


     private RolePracticeId id;
     private Practice practice;
     private Role role;
     private String creationUser;
     private Date creationDate;
     private String modificationUser;
     private Date modificationDate;
     private int active;
     private String audit;
     private Set<Questionnaire> questionnaires = new HashSet<Questionnaire>(0);

    public RolePractice() {
    }

	
    public RolePractice(RolePracticeId id, Practice practice, Role role, String creationUser, Date creationDate, int active, String audit) {
        this.id = id;
        this.practice = practice;
        this.role = role;
        this.creationUser = creationUser;
        this.creationDate = creationDate;
        this.active = active;
        this.audit = audit;
    }
    public RolePractice(RolePracticeId id, Practice practice, Role role, String creationUser, Date creationDate, String modificationUser, Date modificationDate, int active, String audit, Set<Questionnaire> questionnaires) {
       this.id = id;
       this.practice = practice;
       this.role = role;
       this.creationUser = creationUser;
       this.creationDate = creationDate;
       this.modificationUser = modificationUser;
       this.modificationDate = modificationDate;
       this.active = active;
       this.audit = audit;
       this.questionnaires = questionnaires;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idRole", column=@Column(name="id_role", nullable=false) ), 
        @AttributeOverride(name="idPractice", column=@Column(name="id_practice", nullable=false) ) } )
    public RolePracticeId getId() {
        return this.id;
    }
    
    public void setId(RolePracticeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_practice", nullable=false, insertable=false, updatable=false)
    public Practice getPractice() {
        return this.practice;
    }
    
    public void setPractice(Practice practice) {
        this.practice = practice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_role", nullable=false, insertable=false, updatable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="creation_user", nullable=false)
    public String getCreationUser() {
        return this.creationUser;
    }
    
    public void setCreationUser(String creationUser) {
        this.creationUser = creationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="modification_user")
    public String getModificationUser() {
        return this.modificationUser;
    }
    
    public void setModificationUser(String modificationUser) {
        this.modificationUser = modificationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modification_date", length=13)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }

    
    @Column(name="audit", nullable=false)
    public String getAudit() {
        return this.audit;
    }
    
    public void setAudit(String audit) {
        this.audit = audit;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rolePractice")
    public Set<Questionnaire> getQuestionnaires() {
        return this.questionnaires;
    }
    
    public void setQuestionnaires(Set<Questionnaire> questionnaires) {
        this.questionnaires = questionnaires;
    }




}


