package es.upv.dsic.quep.model;
// Generated 10-ago-2016 23:05:31 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePracticeId generated by hbm2java
 */
@Embeddable
public class RolePracticeId  implements java.io.Serializable {


     private int idRole;
     private int idPractice;

    public RolePracticeId() {
    }

    public RolePracticeId(int idRole, int idPractice) {
       this.idRole = idRole;
       this.idPractice = idPractice;
    }
   


    @Column(name="id_role", nullable=false)
    public int getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }


    @Column(name="id_practice", nullable=false)
    public int getIdPractice() {
        return this.idPractice;
    }
    
    public void setIdPractice(int idPractice) {
        this.idPractice = idPractice;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolePracticeId) ) return false;
		 RolePracticeId castOther = ( RolePracticeId ) other; 
         
		 return (this.getIdRole()==castOther.getIdRole())
 && (this.getIdPractice()==castOther.getIdPractice());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRole();
         result = 37 * result + this.getIdPractice();
         return result;
   }   


}


