package es.upv.dsic.quep.model;
// Generated 04-ago-2016 14:00:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Technique generated by hbm2java
 */
@Entity
@Table(name="technique"
    ,schema="public"
)
public class Technique  implements java.io.Serializable {


     private int id;
     private Practice practice;
     private ResilienceCharacteristic resilienceCharacteristic;
     private String abbreviation;
     private String name;
     private String creationUser;
     private Date creationDate;
     private String modificationUser;
     private Date modificationDate;
     private int active;
     private String audit;
     private Set<QuepQuestionTechnique> quepQuestionTechniques = new HashSet<QuepQuestionTechnique>(0);

    public Technique() {
    }

	
    public Technique(int id, Practice practice, String name, String creationUser, String modificationUser, int active, String audit) {
        this.id = id;
        this.practice = practice;
        this.name = name;
        this.creationUser = creationUser;
        this.modificationUser = modificationUser;
        this.active = active;
        this.audit = audit;
    }
    public Technique(int id, Practice practice, ResilienceCharacteristic resilienceCharacteristic, String abbreviation, String name, String creationUser, Date creationDate, String modificationUser, Date modificationDate, int active, String audit, Set<QuepQuestionTechnique> quepQuestionTechniques) {
       this.id = id;
       this.practice = practice;
       this.resilienceCharacteristic = resilienceCharacteristic;
       this.abbreviation = abbreviation;
       this.name = name;
       this.creationUser = creationUser;
       this.creationDate = creationDate;
       this.modificationUser = modificationUser;
       this.modificationDate = modificationDate;
       this.active = active;
       this.audit = audit;
       this.quepQuestionTechniques = quepQuestionTechniques;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_practice", nullable=false)
    public Practice getPractice() {
        return this.practice;
    }
    
    public void setPractice(Practice practice) {
        this.practice = practice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_resilience")
    public ResilienceCharacteristic getResilienceCharacteristic() {
        return this.resilienceCharacteristic;
    }
    
    public void setResilienceCharacteristic(ResilienceCharacteristic resilienceCharacteristic) {
        this.resilienceCharacteristic = resilienceCharacteristic;
    }

    
    @Column(name="abbreviation")
    public String getAbbreviation() {
        return this.abbreviation;
    }
    
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="creation_user", nullable=false)
    public String getCreationUser() {
        return this.creationUser;
    }
    
    public void setCreationUser(String creationUser) {
        this.creationUser = creationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="modification_user", nullable=false)
    public String getModificationUser() {
        return this.modificationUser;
    }
    
    public void setModificationUser(String modificationUser) {
        this.modificationUser = modificationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modification_date", length=13)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }

    
    @Column(name="audit", nullable=false)
    public String getAudit() {
        return this.audit;
    }
    
    public void setAudit(String audit) {
        this.audit = audit;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="technique")
    public Set<QuepQuestionTechnique> getQuepQuestionTechniques() {
        return this.quepQuestionTechniques;
    }
    
    public void setQuepQuestionTechniques(Set<QuepQuestionTechnique> quepQuestionTechniques) {
        this.quepQuestionTechniques = quepQuestionTechniques;
    }




}


